#!/bin/sh
set -e
#set -x

if [ ${USER} = "root" ]; then
   echo "You can't be root to do this." 1>&2
   exit 100
fi

if [ -n "$1" ]; then
    COMPJSON=$1
    export COMPOSER_ALLOW_SUPERUSER=1 
    export COMPOSER_HOME="/var/lib/composer/"

    PROJECT_DIR=$(dirname ${COMPJSON})
    APP=$(basename ${PROJECT_DIR})

    VENDOR_DIR="/var/lib/composer/$APP"

//  jq '.config."vendor-dir" = "$VENDOR_DIR"' $COMPJSON | sponge $COMPJSON

    echo ProjectDir: $PROJECT_DIR VendorDir: $VENDOR_DIR

    echo "${UPDATE_COMMAND} -d ${PROJECT_DIR}"

#    composer -q --no-ansi -n -o --no-dev update --no-interaction --no-progress --no-scripts  -d ${PROJECT_DIR}
    composer -v --no-ansi -n -o --no-dev update --no-interaction --no-progress --no-scripts  -d ${PROJECT_DIR}

    ls $VENDOR_DIR/autoload.php
else
  echo "please call me with path to composer.json "
fi
