#!/bin/sh
set -e
. /usr/share/debconf/confmodule

if [ -n "$1" ]; then
    APP=$1
	db_get composer/WEB_USER || true
	WEB_USER=$(echo $RET | awk -F: '{print $1}')
	WEB_GROUP=$(echo $RET | awk -F: '{print $2}')
	if [ -z ${WEB_GROUP} ]; then
	    WEB_GROUP=${WEB_USER}
	fi

	# creating WEB User group if it isn't already there
	if ! getent group ${WEB_GROUP} >/dev/null; then
    	    addgroup --system --force-badname --quiet ${WEB_GROUP}
	fi

	# creating web user if it isn't already there
	if ! getent passwd $WEB_USER >/dev/null; then
    	    adduser --system --force-badname --quiet \
        	--ingroup ${WEB_GROUP} \
                --home /var/www --no-create-home \
	        --shell /bin/false \
    	    ${WEB_USER}
        usermod -c "Webserver data" $WEB_SERVER
fi


	echo '{}' > /usr/lib/$APP/composer.lock
	chown $WEB_USER /usr/lib/${APP}/composer.lock
	COMPOSER_ALLOW_SUPERUSER=1 COMPOSER_HOME="/var/lib/composer" composer -o install -d /usr/lib/${APP}/ --no-ansi --no-dev --no-interaction --no-progress --no-scripts --optimize-autoloader

	if [ -z $WEB_GROUP ] ; then
	    chown $WEB_USER /var/lib/composer/ /usr/lib/$APP -R
	else
	    id -g $WEB_GROUP &>/dev/null || groupadd $WEB_USER
	    mkdir -p /usr/lib/${APP}
	    chown ${WEB_USER}:${WEB_GROUP} /var/lib/composer/ /usr/lib/${APP} -R
	fi

else
  echo "please call me with app name"
fi
