#!/bin/sh

# Source debconf library.
. /usr/share/debconf/confmodule
db_get composer/WEB_USER
WEBUSER=$(echo  $RET | awk -F: '{print $1}')

UPDATEONLY=$1

case "$1" in
    "")

	ls /usr/share/*/composer.json /usr/*/*/composer.json  | while read project; do
	    PROJECTDIR=$(dirname $project)

	    echo Updating optimized `basename $PROJECTDIR`
	    su - $WEBUSER -s /bin/bash -c 'COMPOSER_HOME="/var/lib/composer" composer -n -o --no-dev update -d ${PROJECTDIR}'

	done

    ;;

    -h|--help)

        echo $0 depname - update only projects requiring given dependency 

    ;;

    *)
	egrep -ilr --include=composer.json "$1" /usr/*/*/composer.json | while read project; do
	    PROJECTDIR=$(dirname $project)
	    echo Updating optimized `basename ${PROJECTDIR}` requiring $1
	    su - $WEBUSER -s /bin/bash -c 'COMPOSER_HOME="/var/lib/composer" composer -n -o --no-dev update -d ${PROJECTDIR}'
	done

    ;;
esac


