#!/bin/sh

#DEBHELPER#

set -e

. /usr/share/debconf/confmodule
db_version 2.0


db_input low composer/UPDATE_APPS || true
db_input low composer/WEB_USER || true
db_go || true

#    echo composer-global-update composer/UPDATE_APPS boolean true     | debconf-set-selections
#    echo composer-global-update composer/WEB_USER    string  www-data | debconf-set-selections

